version: '3.8'

services:
  db:
    image: pgvector/pgvector:pg17
    container_name: job_intel_pgvector
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=job_intel
    ports:
      - "5432:5432"
    volumes:
      - ./data/pg_data:/var/lib/postgresql/data
      - ./docs/sql:/docker-entrypoint-initdb.d
    restart: always
